### PR TITLE
my schema was none, but it should have been dbo, added a patch

### PR DESCRIPTION
**Pull request by waynenilsen**
This fixed a bug that I encountered, not sure if this is the best way to handle it but the patch worked out for me. Let me know if you want any changes.

### CODE REVIEW

**Comment by ksindi** [comment]
@waynenilsen thanks for your contribution. Can you please why `dbo.` fixes it?

**Comment by waynenilsen** [comment]
I just learned now that it is a Microsoft SQL Server thing. It is the default schema in SQL Server. I thought it applied to other dbms but perhaps not. I am using a connection string like [this one](https://stackoverflow.com/a/44764826/2075745)

**Comment by ksindi** [comment]
Got it. Thanks for attempt. Going to close this for now. But please create a new PR if you think of a more general solution. This issue has come up a couple times. Wonder if it's a Microsoft SQL Server-specific issue.

**Comment by waynenilsen** [comment]
I pushed another change to the same branch, not sure if I have to open a new PR now that you have closed this one. I used a more general solution similar to the other PR, this should work on other DBs

**Comment by ksindi** [comment]
Thank @waynenilsen. Looks good. Aiming to deploy a new version to PyPI in the next couple weeks.

**Pull request merged**
